### ISSUE TITLE
Python wrapper broken

### ISSUE THREAD

**Issue by vincebel8** [RI-SE/iso22133#43]
Sometime after initial release v1.0.0, using setup.py to build and install a Python extension appears to be broken. 

After performing a git bisect, it looks like the last working commit for me is 76fc755, and the first bad commit is 116aab7. I tried this on a couple different machines to rule out an environment issue.

In certain commits between 116aab7 and present, when running `python3 setup.py build_ext`, I get errors such as:

```
/home/vincebel/iso22133-test/iso22133.h:451:1: error: unknown type name ‘ISOMessageReturnValue’; use ‘enum’ keyword to refer to the type
  451 | ISOMessageReturnValue decodeDCTIMessage(const char *dctiDataBuffer, const size_t bufferLength, DctiMessageDataType* dctiData, const char debug);
      | ^~~~~~~~~~~~~~~~~~~~~
      | enum 
```

or, more commonly (such as on current master / 323bcd5):

```
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -c iso22133.c -o build/temp.linux-x86_64-3.10/iso22133.o
iso22133.c:2:10: fatal error: header.h: No such file or directory
    2 | #include "header.h"
      |          ^~~~~~~~~~

```
